#!/bin/bash
# Harbor 部署执行脚本
# 请在终端中手动执行此脚本

echo "=========================================="
echo "  Harbor 部署步骤"
echo "=========================================="
echo ""
echo "准备工作已完成 ✓"
echo "  - Harbor安装包已下载"
echo "  - 配置文件已创建"
echo "  - 数据目录已创建"
echo ""
echo "=========================================="
echo ""

echo "步骤1: 准备Harbor配置"
echo "----------------------------------------"
echo "执行命令:"
echo "  cd /Users/hanhailong01/Downloads/my_cloud/harbor/harbor"
echo "  sudo ./prepare"
echo ""
echo "预期输出:"
echo "  - prepare base dir is set to ..."
echo "  - Generated configuration file: ..."
echo "  - Successfully called func: create_root_cert"
echo "  - Generated and saved secret to file: ..."
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "步骤2: 加载Harbor镜像"
echo "----------------------------------------"
echo "执行命令:"
echo "  cd /Users/hanhailong01/Downloads/my_cloud/harbor/harbor"
echo "  sudo docker load -i harbor.v2.11.0.tar.gz"
echo ""
echo "预期输出:"
echo "  - Loaded image: goharbor/harbor-core:v2.11.0"
echo "  - Loaded image: goharbor/harbor-portal:v2.11.0"
echo "  - ... (更多镜像)"
echo ""
echo "⏰ 此步骤需要 5-10 分钟"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "步骤3: 启动Harbor"
echo "----------------------------------------"
echo "执行命令:"
echo "  cd /Users/hanhailong01/Downloads/my_cloud/harbor/harbor"
echo "  sudo docker-compose up -d"
echo ""
echo "预期输出:"
echo "  - Creating harbor-log ... done"
echo "  - Creating harbor-db ... done"
echo "  - Creating registry ... done"
echo "  - Creating harbor-portal ... done"
echo "  - Creating harbor-core ... done"
echo "  - Creating nginx ... done"
echo ""
echo "⏰ 此步骤需要 2-3 分钟"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "步骤4: 检查Harbor状态"
echo "----------------------------------------"
echo "执行命令:"
echo "  cd /Users/hanhailong01/Downloads/my_cloud/harbor/harbor"
echo "  docker-compose ps"
echo ""
echo "预期输出: 所有容器状态为 Up 或 Up (healthy)"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "步骤5: 访问Harbor UI"
echo "----------------------------------------"
echo "1. 打开浏览器"
echo "2. 访问: http://localhost:8093"
echo "3. 登录信息:"
echo "   用户名: admin"
echo "   密码: Harbor12345"
echo ""
read -p "登录成功后按回车继续..."
echo ""

echo "=========================================="
echo "  基础测试"
echo "=========================================="
echo ""

echo "测试1: 创建项目"
echo "----------------------------------------"
echo "在Harbor UI中:"
echo "1. 点击 '新建项目'"
echo "2. 项目名称: mycloud"
echo "3. 访问级别: 私有"
echo "4. 点击 '确定'"
echo ""
read -p "完成后按回车继续..."
echo ""

echo "测试2: Docker登录"
echo "----------------------------------------"
echo "执行命令:"
echo "  docker login localhost:8093 -u admin -p Harbor12345"
echo ""
echo "预期输出: Login Succeeded"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "测试3: 推送测试镜像"
echo "----------------------------------------"
echo "执行命令:"
echo "  docker pull nginx:alpine"
echo "  docker tag nginx:alpine localhost:8093/mycloud/nginx:test"
echo "  docker push localhost:8093/mycloud/nginx:test"
echo ""
echo "预期输出: 推送成功"
echo "在Harbor UI中应该能看到 mycloud/nginx 镜像"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "测试4: 拉取镜像"
echo "----------------------------------------"
echo "执行命令:"
echo "  docker rmi localhost:8093/mycloud/nginx:test"
echo "  docker pull localhost:8093/mycloud/nginx:test"
echo ""
echo "预期输出: 拉取成功"
echo ""
read -p "执行完成后按回车继续..."
echo ""

echo "=========================================="
echo "  🎉 Harbor部署完成！"
echo "=========================================="
echo ""
echo "访问信息:"
echo "  URL: http://localhost:8093"
echo "  用户名: admin"
echo "  密码: Harbor12345"
echo ""
echo "常用命令:"
echo "  查看状态: cd harbor/harbor && docker-compose ps"
echo "  查看日志: cd harbor/harbor && docker-compose logs -f"
echo "  重启: cd harbor/harbor && docker-compose restart"
echo ""
echo "下一步:"
echo "  查看迁移计划:"
echo "  cat /Users/hanhailong01/Downloads/my_cloud/docs/HARBOR_MIGRATION_PLAN.md"
echo ""
