{{- if .Values.istio.enabled }}
{{- $fullName := include "mycloud-app.fullname" . }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mycloud-app.labels" . | nindent 4 }}
    {{- with .Values.istio.destinationRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.istio.destinationRule.host | default $fullName }}
  {{- with .Values.istio.destinationRule.exportTo }}
  exportTo:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  subsets:
  {{- range .Values.istio.destinationRule.subsets }}
  - name: {{ .name | default "stable" }}
    labels:
    {{- toYaml .labels | nindent 6 }}
    {{- with .trafficPolicy }}
    trafficPolicy:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
